---
version: 4.8.0
name: Selenium Chrome
slug: selenium_chrome
description: Selenium Grid Server for Home Assistant support.
url: >-
  https://github.com/SeleniumHQ/docker-selenium
arch:
  - aarch64
  - amd64
  - i386
hassio_api: true
ingress: true
ingress_port: 7900
ingress_entry: vnc.html?autoconnect=true&path=api/hassio_ingress/selenium_chrome/websockify
image: selenium/standalone-chrome
timeout: 30
panel_icon: mdi:web-box
init: false
ports:
  4444/tcp: 4444
  5900/tcp: 5900
  7900/tcp: 7900
ports_description:
  4444/tcp: Your Web Driver
  5900/tcp: vnc Server
  7900/tcp: noVNC to allow users inspect visually container activity with their browser
startup: services