---
version: 4.8.0
name: Selenium Firefox
slug: selenium_firefox
description: Selenium Grid Server for Home Assistant support.
url: >-
  https://github.com/SeleniumHQ/docker-selenium
arch:
  - aarch64
  - amd64
  - i386
ingress: true
ingress_port: 7900
image: selenium/standalone-firefox
timeout: 30
panel_icon: mdi:web-box
init: false
ports:
  4444/tcp: 4444
  7900/tcp: 7900
ports_description:
  4444/tcp: Your Web Driver
  7900/tcp: noVNC to allow users inspect visually container activity with their browser
startup: services