---
version: 4.8.0
name: Seleniarm Chrome
slug: seleniarm_chrome
description: Selenium Grid Server for Home Assistant support.
url: >-
  https://github.com/seleniumhq-community/docker-seleniarm
arch:
  - armhf
  - armv7
hassio_api: true
ingress: true
ingress_port: 7900
ingress_entry: vnc.html?autoconnect=true&path=api/hassio_ingress/seleniarm_chrome/websockify
image: seleniarm/standalone-chrome
timeout: 30
panel_icon: mdi:web-box
init: false
ports:
  4444/tcp: 4444
  7900/tcp: 7900
ports_description:
  4444/tcp: Your Web Driver
  7900/tcp: noVNC to allow users inspect visually container activity with their browser
startup: services